// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "go-telemedicine/models"

	mock "github.com/stretchr/testify/mock"
)

// UserPermissionRepositoryInterface is an autogenerated mock type for the UserPermissionRepositoryInterface type
type UserPermissionRepositoryInterface struct {
	mock.Mock
}

// AssignRoleToUserRequest provides a mock function with given fields: req
func (_m *UserPermissionRepositoryInterface) AssignRoleToUserRequest(req models.AssignRoleToUserRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUserRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.AssignRoleToUserRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePermission provides a mock function with given fields: req
func (_m *UserPermissionRepositoryInterface) CreatePermission(req models.PermissionModels) (int64, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.PermissionModels) (int64, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(models.PermissionModels) int64); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.PermissionModels) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRolePermission provides a mock function with given fields: req
func (_m *UserPermissionRepositoryInterface) CreateRolePermission(req models.RolePermissionModels) (int64, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRolePermission")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.RolePermissionModels) (int64, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(models.RolePermissionModels) int64); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.RolePermissionModels) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUserPermission provides a mock function with given fields: req
func (_m *UserPermissionRepositoryInterface) CreateUserPermission(req models.UserPermissionModels) (int64, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserPermission")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.UserPermissionModels) (int64, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(models.UserPermissionModels) int64); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.UserPermissionModels) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindListUserRolePermissions provides a mock function with given fields: userID
func (_m *UserPermissionRepositoryInterface) FindListUserRolePermissions(userID int64) ([]models.UserRolePermissionModels, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindListUserRolePermissions")
	}

	var r0 []models.UserRolePermissionModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]models.UserRolePermissionModels, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) []models.UserRolePermissionModels); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserRolePermissionModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPermissionsForUser provides a mock function with given fields: userID
func (_m *UserPermissionRepositoryInterface) FindPermissionsForUser(userID int64) ([]models.UserRolePermissionModels, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsForUser")
	}

	var r0 []models.UserRolePermissionModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]models.UserRolePermissionModels, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) []models.UserRolePermissionModels); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserRolePermissionModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserRole provides a mock function with given fields: userID
func (_m *UserPermissionRepositoryInterface) FindUserRole(userID int64) (models.FindUserRoleResponse, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserRole")
	}

	var r0 models.FindUserRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (models.FindUserRoleResponse, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) models.FindUserRoleResponse); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(models.FindUserRoleResponse)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleHavePermission provides a mock function with given fields: userID, permissionGroup, permissionName
func (_m *UserPermissionRepositoryInterface) RoleHavePermission(userID int64, permissionGroup string, permissionName string) (bool, error) {
	ret := _m.Called(userID, permissionGroup, permissionName)

	if len(ret) == 0 {
		panic("no return value specified for RoleHavePermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, string) (bool, error)); ok {
		return rf(userID, permissionGroup, permissionName)
	}
	if rf, ok := ret.Get(0).(func(int64, string, string) bool); ok {
		r0 = rf(userID, permissionGroup, permissionName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64, string, string) error); ok {
		r1 = rf(userID, permissionGroup, permissionName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserHavePermission provides a mock function with given fields: userID, permissionGroup, permissionName
func (_m *UserPermissionRepositoryInterface) UserHavePermission(userID int64, permissionGroup string, permissionName string) (bool, error) {
	ret := _m.Called(userID, permissionGroup, permissionName)

	if len(ret) == 0 {
		panic("no return value specified for UserHavePermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, string) (bool, error)); ok {
		return rf(userID, permissionGroup, permissionName)
	}
	if rf, ok := ret.Get(0).(func(int64, string, string) bool); ok {
		r0 = rf(userID, permissionGroup, permissionName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64, string, string) error); ok {
		r1 = rf(userID, permissionGroup, permissionName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserPermissionRepositoryInterface creates a new instance of UserPermissionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPermissionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPermissionRepositoryInterface {
	mock := &UserPermissionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
