name: Run Tests with Coverage

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.3'

    - name: Install dependencies
      run: go mod tidy

    - name: Create and load .env files
      run: |
        touch service/consultationService/.env
        touch service/scheduleService/.env
        touch service/userService/.env

    - name: Run service tests
      run: go test -coverprofile=coverage.out ./service/...

    - name: Generate coverage report
      run: |
        go tool cover -func=coverage.out | tee coverage.txt
        go tool cover -html=coverage.out
